### 1. Write a Python Program to Add Two Matrices?

In [12]:
matrix1 = []
matrix2 = []
r1 = int(input("Enter number of rows: "))
c1 = int(input("Enter number of columns: "))

for i in range(r1):
    row = []
    for j in range(c1):
        ip = int(input("Enter first matrix elements in row wise: "))
        row.append(ip)
    matrix1.append(row)
print(matrix1)

for i in range(r1):
    row = []
    for j in range(c1):
        ip = int(input("Enter second matrix elements in row wise: "))
        row.append(ip)
    matrix2.append(row)
print(matrix2)

print("The addition of two matrix:")
add_mat = [[matrix1[i][j] + matrix2[i][j]  for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
for r in add_mat:
    print(r)
        

Enter number of rows: 2
Enter number of columns: 2
Enter first matrix elements in row wise: 1
Enter first matrix elements in row wise: 2
Enter first matrix elements in row wise: 3
Enter first matrix elements in row wise: 4
[[1, 2], [3, 4]]
Enter second matrix elements in row wise: 4
Enter second matrix elements in row wise: 3
Enter second matrix elements in row wise: 2
Enter second matrix elements in row wise: 1
[[4, 3], [2, 1]]
The addition of two matrix:
[5, 5]
[5, 5]


### 2. Write a Python Program to Multiply Two Matrices?

In [14]:
import numpy as np
matrix1 = []
matrix2 = []
r1 = int(input("Enter number of rows: "))
c1 = int(input("Enter number of columns: "))

for i in range(r1):
    row = []
    for j in range(c1):
        ip = int(input("Enter first matrix elements in row wise: "))
        row.append(ip)
    matrix1.append(row)
print(matrix1)

for i in range(r1):
    row = []
    for j in range(c1):
        ip = int(input("Enter second matrix elements in row wise: "))
        row.append(ip)
    matrix2.append(row)
print(matrix2)

print("the multiplied matrix is: \n", np.multiply(matrix1,matrix2) )

Enter number of rows: 3
Enter number of columns: 3
Enter first matrix elements in row wise: 1
Enter first matrix elements in row wise: 0
Enter first matrix elements in row wise: 0
Enter first matrix elements in row wise: 0
Enter first matrix elements in row wise: 1
Enter first matrix elements in row wise: 0
Enter first matrix elements in row wise: 0
Enter first matrix elements in row wise: 0
Enter first matrix elements in row wise: 1
[[1, 0, 0], [0, 1, 0], [0, 0, 1]]
Enter second matrix elements in row wise: 1
Enter second matrix elements in row wise: 2
Enter second matrix elements in row wise: 3
Enter second matrix elements in row wise: 4
Enter second matrix elements in row wise: 5
Enter second matrix elements in row wise: 6
Enter second matrix elements in row wise: 7
Enter second matrix elements in row wise: 8
Enter second matrix elements in row wise: 9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
the multiplied matrix is: 
 [[1 0 0]
 [0 5 0]
 [0 0 9]]


### 3. Write a Python Program to Transpose a Matrix?

In [15]:
matrix = []
r1 = int(input("Enter number of rows: "))
c1 = int(input("Enter number of columns: "))

for i in range(r1):
    row = []
    for j in range(c1):
        ip = int(input("Enter first matrix elements in row wise: "))
        row.append(ip)
    matrix.append(row)
print(matrix, " is the original matrix")
print("Uts transpose matrix is ", np.transpose(matrix))

Enter number of rows: 2
Enter number of columns: 2
Enter first matrix elements in row wise: 2
Enter first matrix elements in row wise: 3
Enter first matrix elements in row wise: 4
Enter first matrix elements in row wise: 5
[[2, 3], [4, 5]]  is the original matrix
Uts transpose matrix is  [[2 4]
 [3 5]]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [20]:
sentence = input("Enter a sentence : ")
s  = [word.lower() for word in sentence.split()]
print("the sorted order:")
s.sort()
for i in s:
    print(i)

Enter a sentence : hi every one
the sorted order:
every
hi
one


### 5. Write a Python Program to Remove Punctuation From a String?

In [21]:
import re
string = input("enter the sentence ")
result = re.sub(r'[^\w\s]', '', string)
print(" The sentence after punctiation filter is: ", result)


enter the sentence "hello guys"
 The sentence after punctiation filter is:  hello guys
